# GitHub Sponsor-knapp: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# Buy Me a Coffee: https://www.buymeacoffee.com/andnil84
buy_me_a_coffee: andnil84
